############################# English ############################
[en]
languageName = "En"
title = "egovzm.org"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
footer_content = "" 
# copyright
copyright = "Designed by [ITM Consult (ZM)]"
