############################# English ############################
[en]
languageName = "En"
title = "ITM Consult (ZM)"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = " "
footer_menu_middle = ""
footer_menu_right = ""
footer_content = "Our mission is to empower organisations to achieve innovative data-driven solutions that enable them to build capacity, inform their decision-making, solve their most important challenges and thrive" 
# copyright
copyright = "Designed by [ITM Consult (ZM)]"
