############################# English ############################
[en]
languageName = "En"
title = "ITM Consult"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = ""
footer_menu_middle = ""
footer_menu_right = ""
footer_content = "itmconsultzm@gmail.com     +260.976.242.2222" 
# copyright
copyright = "Designed by Comdev Networks"
